Update Jenkinsfile1

diff --git a/Jenkinsfile1 b/Jenkinsfile1
--- a/Jenkinsfile1
+++ b/Jenkinsfile1
@@ -85,6 +85,50 @@ pipeline {
         }
     }
 }
+   stage('Create EKS Cluster') {
+    steps {
+        script {
+            sh '''
+            echo "☸️ Checking if EKS cluster '${EKS_CLUSTER_NAME}' exists..."
+            if ! eksctl get cluster --region ${AWS_REGION} | grep -q ${EKS_CLUSTER_NAME}; then
+                echo "🚀 Cluster not found — creating new EKS cluster: ${EKS_CLUSTER_NAME}"
+
+                cat <<EOF > eks-cluster.yaml
+apiVersion: eksctl.io/v1alpha5
+kind: ClusterConfig
+
+metadata:
+  name: ${EKS_CLUSTER_NAME}
+  region: ${AWS_REGION}
+  version: "1.29"
+
+vpc:
+  cidr: 172.31.0.0/16
+
+nodeGroups:
+  - name: ng-app
+    instanceType: t3.micro
+    desiredCapacity: 2
+    minSize: 1
+    maxSize: 3
+    iam:
+      withAddonPolicies:
+        imageBuilder: true
+        autoScaler: true
+        ebs: true
+        albIngress: true
+        cloudWatch: true
+EOF
+
+                eksctl create cluster -f eks-cluster.yaml
+            else
+                echo "✅ EKS cluster '${EKS_CLUSTER_NAME}' already exists. Skipping creation."
+            fi
+            '''
+        }
+    }
+}
+
     stage('Deploy to EKS Cluster') {
             steps {
                 script {
